baseURL = 'https://tassiluca.github.io/direct-style-experiments/'
languageCode = 'en-us'
title = 'direct-style-experiments'

enableGitInfo = true # to enable 'Last Modified by' date and git author information on 'doc' type pages.

[markup]
  [markup.highlight]
    style = 'catppuccin-latte'
  [goldmark.renderer]
    unsafe = true

[module]
    [[module.imports]]
        path = 'github.com/alex-shpak/hugo-book'

[params]
    BookTheme = 'light'
    BookRepo = 'https://github.com/tassiLuca/direct-style-experiments' # used for 'Last Modified' and 'Edit this page' links
    BookCommitPath = 'commit'
